services:
  dev:
    container_name: timpietyper-api-dev
    image: timpietyper-api
    build:
      context: .
    ports:
      - "5278:5278"
    volumes:
      - .:/app 
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - timpietyper_default

  db:
    container_name: timpietyper-db
    image: mysql:8
    ports:
      - "5371:3306"
    environment:
      - MYSQL_DATABASE=db_timpietyper
      - MYSQL_ROOT_PASSWORD=123 
    volumes:
      - timpietyper_data:/var/lib/mysql 
    networks:
      - timpietyper_default

volumes:
  timpietyper_data:

networks:
  timpietyper_default:
    external: true